name: nvm_install_and_use
description: nvm install & use

runs:
  using: composite
  steps:
    - name: node --version (before)
      shell: bash
      run: node --version
      continue-on-error: true

    # runs nvm use as well
    - name: nvm install
      # WARNING: nvm is "not found" w/o this
      shell: bash -l {0}
      run: nvm install --no-progress

    - name: node --version (after)
      shell: bash
      run: node --version

    - name: npm --version
      shell: bash
      run: npm --version
