name: "[C]ontinuous [I]ntegration"

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/install_and_use
      - uses: percebus/github-actions-npm/.github/actions/install@main

      - name: npm run lint
        run: npm run lint
