name: Test actions/install_and_use

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/install_and_use

      - name: node --version
        run: node --version

  # npmrc__matrix:
  #   needs: default
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     max-parallel: 6
  #     matrix:
  #       node-version:
  #         # As of 2025-05-04
  #         - default # 20?
  #         - lts # 22
  #         - stable # 23
  #         - latest # 24
  #         - root

  #   name: node @ ${{ matrix.node-version }}
  #   steps:
  #     # Is it because the matrix needs to be pre-rendered?
  #     # - uses: ./.github/actions/install_and_use # FIXME: why doesn't this work?
  #     - uses: percebus/github-actions-node/.github/actions/install_and_use@main # XXX
  #       with:
  #         working-directory: assets/node/${{ matrix.node-version }}

  #     - name: node --version
  #       run: node --version
